import { IiconArrElement } from './interfaces';

export const iconArr: IiconArrElement[] = [
  {
    code: 1000,
    day: 'Sunny',
    night: 'Clear',
    icon: 'fa fa-sun',
  },
  {
    code: 1003,
    day: 'Partly cloudy',
    night: 'Partly cloudy',
    icon: 'fa fa-cloud-sun',
  },
  {
    code: 1006,
    day: 'Cloudy',
    night: 'Cloudy',
    icon: 'fa fa-cloud',
  },
  {
    code: 1009,
    day: 'Overcast',
    night: 'Overcast',
    icon: 'fa fa-cloud',
  },
  {
    code: 1030,
    day: 'Mist',
    night: 'Mist',
    icon: 'fa fa-cloud',
  },
  {
    code: 1063,
    day: 'Patchy rain possible',
    night: 'Patchy rain possible',
    icon: 'fa fa-cloud-sun-rain',
  },
  {
    code: 1066,
    day: 'Patchy snow possible',
    night: 'Patchy snow possible',
    icon: 'fa fa-snowflake',
  },
  {
    code: 1069,
    day: 'Patchy sleet possible',
    night: 'Patchy sleet possible',
    icon: 'fa fa-cloud-showers-heavy',
  },
  {
    code: 1072,
    day: 'Patchy freezing drizzle possible',
    night: 'Patchy freezing drizzle possible',
    icon: 'fa fa-cloud-rain',
  },
  {
    code: 1087,
    day: 'Thundery outbreaks possible',
    night: 'Thundery outbreaks possible',
    icon: 'fa fa-cloud-rain',
  },
  {
    code: 1114,
    day: 'Blowing snow',
    night: 'Blowing snow',
    icon: 'fa fa-snowflake',
  },
  {
    code: 1117,
    day: 'Blizzard',
    night: 'Blizzard',
    icon: 'fa fa-snowflake',
  },
  {
    code: 1135,
    day: 'Fog',
    night: 'Fog',
    icon: 'fa fa-smog',
  },
  {
    code: 1147,
    day: 'Freezing fog',
    night: 'Freezing fog',
    icon: 'fa fa-smog',
  },
  {
    code: 1150,
    day: 'Patchy light drizzle',
    night: 'Patchy light drizzle',
    icon: 'fa fa-cloud-rain',
  },
  {
    code: 1153,
    day: 'Light drizzle',
    night: 'Light drizzle',
    icon: 'fa fa-cloud-rain',
  },
  {
    code: 1168,
    day: 'Freezing drizzle',
    night: 'Freezing drizzle',
    icon: 'fa fa-cloud-rain',
  },
  {
    code: 1171,
    day: 'Heavy freezing drizzle',
    night: 'Heavy freezing drizzle',
    icon: 'fa fa-cloud-rain',
  },
  {
    code: 1180,
    day: 'Patchy light rain',
    night: 'Patchy light rain',
    icon: 'fa fa-cloud-sun-rain',
  },
  {
    code: 1183,
    day: 'Light rain',
    night: 'Light rain',
    icon: 'fa fa-cloud-sun-rain',
  },
  {
    code: 1186,
    day: 'Moderate rain at times',
    night: 'Moderate rain at times',
    icon: 'fa fa-cloud-sun-rain',
  },
  {
    code: 1189,
    day: 'Moderate rain',
    night: 'Moderate rain',
    icon: 'fa fa-cloud-showers',
  },
  {
    code: 1192,
    day: 'Heavy rain at times',
    night: 'Heavy rain at times',
    icon: 'fa fa-cloud-showers-heavy',
  },
  {
    code: 1195,
    day: 'Heavy rain',
    night: 'Heavy rain',
    icon: 'fa fa-cloud-showers-heavy',
  },
  {
    code: 1198,
    day: 'Light freezing rain',
    night: 'Light freezing rain',
    icon: 'fa fa-cloud-showers-heavy',
  },
  {
    code: 1201,
    day: 'Moderate or heavy freezing rain',
    night: 'Moderate or heavy freezing rain',
    icon: 'fa fa-cloud-showers-heavy',
  },
  {
    code: 1204,
    day: 'Light sleet',
    night: 'Light sleet',
    icon: 'fa fa-cloud-sleet',
  },
  {
    code: 1207,
    day: 'Moderate or heavy sleet',
    night: 'Moderate or heavy sleet',
    icon: 'fa fa-snowflake',
  },
  {
    code: 1210,
    day: 'Patchy light snow',
    night: 'Patchy light snow',
    icon: 'fa fa-snowflake',
  },
  {
    code: 1213,
    day: 'Light snow',
    night: 'Light snow',
    icon: 'fa fa-snowflake',
  },
  {
    code: 1216,
    day: 'Patchy moderate snow',
    night: 'Patchy moderate snow',
    icon: 'fa fa-snowflake',
  },
  {
    code: 1219,
    day: 'Moderate snow',
    night: 'Moderate snow',
    icon: 'fa fa-snowflake',
  },
  {
    code: 1222,
    day: 'Patchy heavy snow',
    night: 'Patchy heavy snow',
    icon: 'fa fa-snowflake',
  },
  {
    code: 1225,
    day: 'Heavy snow',
    night: 'Heavy snow',
    icon: 'fa fa-snowflake',
  },
  {
    code: 1237,
    day: 'Ice pellets',
    night: 'Ice pellets',
    icon: 'fa fa-cloud-meatball',
  },
  {
    code: 1240,
    day: 'Light rain shower',
    night: 'Light rain shower',
    icon: 'fa fa-cloud-rain',
  },
  {
    code: 1243,
    day: 'Moderate or heavy rain shower',
    night: 'Moderate or heavy rain shower',
    icon: 'fa fa-cloud-showers-heavy',
  },
  {
    code: 1246,
    day: 'Torrential rain shower',
    night: 'Torrential rain shower',
    icon: 'fa fa-cloud-showers-heavy',
  },
  {
    code: 1249,
    day: 'Light sleet showers',
    night: 'Light sleet showers',
    icon: 'fa fa-snowflake',
  },
  {
    code: 1252,
    day: 'Moderate or heavy sleet showers',
    night: 'Moderate or heavy sleet showers',
    icon: 'fa fa-snowflake',
  },
  {
    code: 1255,
    day: 'Light snow showers',
    night: 'Light snow showers',
    icon: 'fa fa-snowflake',
  },
  {
    code: 1258,
    day: 'Moderate or heavy snow showers',
    night: 'Moderate or heavy snow showers',
    icon: 'fa fa-snowflake',
  },
  {
    code: 1261,
    day: 'Light showers of ice pellets',
    night: 'Light showers of ice pellets',
    icon: 'fa fa-snowflake',
  },
  {
    code: 1264,
    day: 'Moderate or heavy showers of ice pellets',
    night: 'Moderate or heavy showers of ice pellets',
    icon: 'fa fa-cloud-meatball',
  },
  {
    code: 1273,
    day: 'Patchy light rain with thunder',
    night: 'Patchy light rain with thunder',
    icon: 'fa fa-cloud-sun-rain',
  },
  {
    code: 1276,
    day: 'Moderate or heavy rain with thunder',
    night: 'Moderate or heavy rain with thunder',
    icon: 'fa fa-bolt',
  },
  {
    code: 1279,
    day: 'Patchy light snow with thunder',
    night: 'Patchy light snow with thunder',
    icon: 'fa fa-bolt',
  },
  {
    code: 1282,
    day: 'Moderate or heavy snow with thunder',
    night: 'Moderate or heavy snow with thunder',
    icon: 'fa fa-bolt',
  },
];
